### ISSUE TITLE
FEATURE REQUEST: Please add Prediction result to the *-ranked.tsv

### ISSUE THREAD

**Issue by xizhesun** [ccdmb/predector#47]
Hi Darcy,

I found that Only the Probability scores of ApoplastP were shown in the rank list. But the score does not indicate whether it is an apoplast effector. I think we should add the Prediction result of ApoplastP to the *-ranked.tsv. 

Have a nice weekend!
Xizhe

**Comment by darcyabjones** [comment]
The score is corrected so that it always refers to the classification probability that its apoplastic or an effector.
These ones are all binary outcomes, so 1-p gives the inverse.

For EP3 we'll have to include the prediction since there are three categories.

Have a bit of description here, but I'll make it a bit clearer for anyone else.
https://github.com/ccdmb/predector/wiki#-rankedtsv

**Comment by xizhesun** [comment]
I see that description now. "1-p" is even better for data analysis. Thanks! Have a nice weekend!
