### ISSUE TITLE
BUG: Conda registration of signalp-4.1g.Linux.tar.gz & phobius101_linux.tar.gz

### ISSUE THREAD

**Issue by tdymc** [ccdmb/predector#68]
**Describe the bug**
"ERROR: One or more of the proprietary package registrations failed." signalp-4.1g.Linux.tar.gz
"ERROR: One or more of the proprietary package registrations failed." phobius101_linux.tar.gz

**Screenshots or copy-pasted terminal output **
Two provided below, separated by line:

Registering source file signalp-4.1g.Linux.tar.gz for signalp4 into conda environment at:
/home/user/.conda/envs/predector/share/signalp4-4.1g-2

Unregistering old source files if they exist.

patching file signalp
Finished registering signalp4.
Testing installation...
Cwd.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xde00080)

------------------------------------------------------------------------------------------------------------------------

phobius-register phobius101_linux.tar.gz
Registering source file phobius101_linux.tar.gz for phobius into conda environment at:
/home/user/.conda/envs/predector/share/phobius-1.01-2

Unregistering old source files if they exist.

patching file phobius.pl
Finished registering phobius.
Testing installation...
Fcntl.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xde00080)

**Operating system (please enter the following information as appropriate):**
 - OS/Linux distribution: Linux on HPC
 - Dependency management: Conda
 - HPC

**Comment by darcyabjones** [comment]
Hey tdymc!

Thanks for reporting the issue.
This looks like your system has some existing perl libraries in your search path, and perl is finding those versions before the ones installed with conda.

Unfortunately this is always a risk with conda, because it isn't isolated from the host OS in the same way that containers are.

Your issue will be pretty specific to your HPC, so I can only make suggestions unless you can share some more info about the environment with me.

1 check to see if perl or any perl library modules are loaded by default (e.g. `module list`). If yes, `module unload` them.
2 check to see if you have any perl paths set: `env | grep -i "perl"`. If yes, try `unset ` -ing those environment variables.

Try re-running the install script after those steps are done (you'll probably need to remove the failed conda environment too `conda env delete -n predector`).
If that works you'll need to remove the same environment variables and unload modules for any future runs as well.

If it doesn't work can you please copy the results of the following commands here for me?
From a new login shell

```
module list
env

conda activate predector
env
```

I.e. i just need to see what environment variables are set before and after loading the conda environment.
Happy for PMs or emails if you're not comfortable sharing the results in public :)


Apologies for the trouble.
Cheers!
Darcy

**Comment by tdymc** [comment]
Thank you Darcy!

I was able to unload perl libraries loaded by default and resolve the problem, the registrations completed successfully and I was able to run the application.

Thank you for your help!

**Comment by darcyabjones** [comment]
Great to hear!

Hope it's useful for you.
I'll add some documentation about this in the common issues section for the next version.

Thanks again for reporting the issue.
Ta,
Darcy
