### ISSUE TITLE
Installation fails when testing DeepLoc

### ISSUE THREAD

**Issue by IdoBar** [ccdmb/predector#79]
I have been trying to install Predector with `mamba` and after solving an [issue](https://github.com/ccdmb/predector/issues/77#issuecomment-1102099317) related to using an older version of `mamba`, the installation succeeds, but registration of `DeepLoc` fails with the following error:
```
AttributeError: module 'typing' has no attribute '_SpecialForm'
```
It appears that you need Python >3.6 for that so when I removed the pinning of the specific Python version in the yaml file (`conda-forge::python=3.6.13`), it installed Python v3.7.12 and the `DeepLoc` registered successfully.

**Comment by darcyabjones** [comment]
Hi @IdoBar 

Sorry for my late response to this. I've been on leave and then got sick.

Thanks for your work figuring this out and the Mamba version issue.
The reason that I had python 3.6 pinned was because of a numpy compatibility issue with Keras and Deepredeff.
But now it seems that 3.6 is too old now.

I'll try to update the conda dependencies over the next few days.
It's always a bit complex to make sure that all of the versions play nicely, and I suspect that I might have to send a PR for Deepredeff.
Fingers crossed it turns out to be easier than I feared :)

Cheers,
Darcy

**Comment by darcyabjones** [comment]
Hi @IdoBar 
Thanks again for reporting this.

I've integrated your change and this should be integrated into the latest release (1.2.6 #83)

Sorry it's taken so long. It's a busy time for me :)

Cheers,
Darcy
